<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbb126b145bd1b1be2c1bab38e0d57a47
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbb126b145bd1b1be2c1bab38e0d57a47::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbb126b145bd1b1be2c1bab38e0d57a47::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
